name: Deploy Ragnarok Server

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-deploy
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@212.83.141.83 -p 2246 << 'EOF'
            cd /root/demo
            git pull origin main --rebase
          EOF

          echo "files updated"
