name: Validate NPC Scripts and DB Changes

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'tools/ci/**'
      - 'db/**'
      - 'npc/**'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest]
          gcc: ['11']
          mode: ['PRE', 'RE']

    steps:
      - uses: actions/checkout@v4

      - name: Variable Parsing - PRE
        if: ${{ matrix.mode == 'PRE' }}
        run: |
          echo "PRERE=yes" >> $GITHUB_ENV
      - name: Variable Parsing - RE
        if: ${{ matrix.mode == 'RE' }}
        run: |
          echo "PRERE=no" >> $GITHUB_ENV

      - name: Update & Install packages
        run: |
          sudo apt update
          sudo apt install zlib1g-dev libpcre3-dev gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}

      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Setup Database and import table data
        run: ./tools/ci/sql.sh

      - name: Command - configure
        env:
            CONFIGURE_FLAGS: 'CC=gcc-${{ matrix.gcc }} CXX=g++-${{ matrix.gcc }} --enable-prere=${{ env.PRERE }} --enable-buildbot=yes'
        run: ./configure $CONFIGURE_FLAGS

      - name: Enable All NPCs for Testing
        run: ./tools/ci/npc.sh

      - name: Command - make clean
        run: make clean

      - name: Command - make import
        run: make import

      - name: Command - make map
        run: make map

      - name: Run Once - map-server
        run: ./map-server --run-once
